### ISSUE TITLE
Cannot read property 'local' of null

### ISSUE THREAD

**Issue by mikolfaro** [pepri/wizdler#13]
Hi,
when I click on a signature of the WSDL it opens the "POST' tab
but the message body shows "Cannot read property 'local' of null" instead of the call stub.

Sadly I did not found a stacktrace in the DeveloperConsole to paste you.

I cannot share the WSDL I'm trying to load (under non-disclosure agreement).
I tried loading a couple of open WSs and they worked just fine,
guess that it's malformed or something.

Thank you for your support

**Comment by pepri** [comment]
Hello,

can SoapUI create a SOAP request for the same method?

Maybe there is xs:include used, which is not supported yet. But I can just guess without the WSDL. You can try to find the line where the error occurs by debugging the editor and checking "Pause on caught exceptions" in the web inspector.

**Comment by mikolfaro** [comment]
SoapUI manages to load the signatures correctly.

I tried debugging the editor a bit.
The exception happens at line 99 of `wsdl.js`, this happens because `this.type` is `undefined`, `el` is an element inside the `soapenv:Header`part of the request

```
$.each(message.parts, function() {
  var el = doc.createElementNS(ctx.operation.name.ns, this.name);
  wrapper.appendChild(el); 
  el.appendChild(document.createTextNode('[' + this.type.local + ']')); // Line 99
});
```

I do not found any include, there are just a few imports.

**Comment by pepri** [comment]
Please try again with the version 1.28, it is probably fixed. I cannot tell more without WSDL - closing.
