### ISSUE TITLE
Wizdler overwrites Command-L shortcut for going to location bar

### ISSUE THREAD

**Issue by pimlottc** [pepri/wizdler#2]
Hitting Command-L (on OSX) on a Wizdler tab does not move focus to the location bar like it normally does in Chrome, but instead opens a dialog box to jump to line number.  This is a very common key combination, perhaps Wizdler could use something else?

**Comment by pepri** [comment]
I disabled the key binding for Command-L, but I do not have OSX to test it. I hope it works, so I am closing this issue.
