### ISSUE TITLE
Wizdler opens request tab in non-incognito window when invoked from incognito window

### ISSUE THREAD

**Issue by pimlottc** [pepri/wizdler#4]
When I try to generate a manual request using Wizdler from an incognito window, it creates the request tab in a non-incognito and doesn't work.
1. Enable Wizdler in incognito mode
2. Open service WSDL in an incognito tab
3. Click the Wizdler icon and select a method

Expected: A new tab for the SOAP request is opened in the same incognito window, containing the XML request template

Actual: A new tab is opened in a normal window, with no content

**Comment by pimlottc** [comment]
This is a particular annoyance in my project as the web services I'm using are protected by SSL client authentication so I use incognito mode to clear my session credentials

**Comment by pepri** [comment]
Fixed in version 1.2.
