### ISSUE TITLE
SOAPAction header value

### ISSUE THREAD

**Issue by dougdew** [pepri/wizdler#5]
How do I set the value for the SOAPAction header?

I'm attempting to perform a SOAP operation, but am receiving an error message from the server because my SOAPAction request header has no value. In other words, this is being sent to the server:

SOAPAction:

Thanks.

**Comment by dougdew** [comment]
I stepped through your code in the debugger and found where the SOAPAction header value is being determined. It seems that the code is expecting the operation element of my wsdl to have an attribute that should specify the soap action. My wsdl doesn't have that. It seems that my wsdl is incorrect.

**Comment by pepri** [comment]
Please provide the WSDL so I can see what is the problem.

**Comment by dougdew** [comment]
Peter,

Thank you for the reply.

I determined that the problem was in the wsdl that I was using.

Thank you again for making your code available for use.

Doug
