### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by EdwardOst** [pepri/wizdler#7]
Is there a way to adjust the timeout for the request?  I have a reasonably long web service invocation, maybe 20 seconds, and the client times out before the response is received.  If this could be configured it would be helpful.

**Comment by pepri** [comment]
There is no timeout set in the client. The default timeout is infinite as per XMLHttpRequest spec. I have just tested that the client did not time out while waiting on the breakpoint set on the server-side for cca 2 minutes.
